Python 2.7:
  script:
  - py_version=2.7
  - EXTRA_INSTALL="numpy pybind11"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml


Python 3.6:
  script:
  - py_version=3.6
  - EXTRA_INSTALL="numpy pybind11"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3.6
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Python 3.7:
  script:
  - py_version=3.7
  - EXTRA_INSTALL="numpy pybind11"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3.7
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Python 2.7 Apple:
  script:
  - export PY_EXE=python2.7
  - export EXTRA_INSTALL="pybind11 numpy"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  - apple
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Documentation:
  script:
  - EXTRA_INSTALL="numpy pybind11"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-docs.sh
  - ". ./build-docs.sh"
  tags:
  - python3.5
  only:
  - master
